using Forge.Infrastructure.Persistence;
using Forge.Shared.Entities;
using Microsoft.EntityFrameworkCore;

namespace Forge.Shared.Identifiers;

public sealed class ForgeUuidGenerator : IForgeUuidGenerator
{
    private readonly AppDbContext _context;

    public ForgeUuidGenerator(AppDbContext context)
    {
        _context = context;
    }

    public Task<Guid> GenerateApplicationUuidAsync(
        CancellationToken cancellationToken = default)
        => GenerateAsync(
            ForgeUuidEntityTypeEntity.Application,
            cancellationToken);

    public Task<Guid> GenerateMetaObjectUuidAsync(
        CancellationToken cancellationToken = default)
        => GenerateAsync(
            ForgeUuidEntityTypeEntity.MetaObject,
            cancellationToken);

    public Task<Guid> GenerateRelationshipUuidAsync(
        CancellationToken cancellationToken = default)
        => GenerateAsync(
            ForgeUuidEntityTypeEntity.Relationship,
            cancellationToken);

    private async Task<Guid> GenerateAsync(
        byte entityType,
        CancellationToken cancellationToken)
    {
        var counter = await _context.Database
        .SqlQuery<long>($"""
            UPDATE UuidCounter
            SET CounterValue = CounterValue + 1
            OUTPUT INSERTED.CounterValue
            WHERE EntityType = {entityType}
            """)
        .SingleAsync(cancellationToken);

        return CreateUuidV7(entityType, counter);
    }

    private static Guid CreateUuidV7(byte entityType, long counter)
    {
        var uuid = Guid.CreateVersion7();

        var hex = uuid.ToString("N");

        // Keep first 20 hex characters generated by UUID v7.
        // Replace final 12 characters with:
        // entity type + 11-character counter.
        var suffix = $"{entityType:X1}{counter:X11}";

        var forgeUuid = hex[..20] + suffix;

        return Guid.ParseExact(forgeUuid, "N");
    }
}