using Forge.Infrastructure.Persistence;
using Forge.Shared.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace Forge.Shared.Identifiers;

public sealed class ForgeUuidGenerator : IForgeUuidGenerator
{
    private readonly AppDbContext _context;

    public ForgeUuidGenerator(AppDbContext context)
    {
        _context = context;
    }

    public Task<Guid> GenerateApplicationUuidAsync(
        CancellationToken cancellationToken = default)
        => GenerateAsync(
            ForgeUuidEntityTypeEntity.Application,
            cancellationToken);

    public Task<Guid> GenerateMetaObjectUuidAsync(
        CancellationToken cancellationToken = default)
        => GenerateAsync(
            ForgeUuidEntityTypeEntity.MetaObject,
            cancellationToken);

    public Task<Guid> GenerateRelationshipUuidAsync(
        CancellationToken cancellationToken = default)
        => GenerateAsync(
            ForgeUuidEntityTypeEntity.Relationship,
            cancellationToken);

    public Task<Guid> GenerateInterfaceUuidAsync(
        CancellationToken cancellationToken = default)
        => GenerateAsync(
            ForgeUuidEntityTypeEntity.Interface,
            cancellationToken);

    private async Task<Guid> GenerateAsync(
        byte entityType,
        CancellationToken cancellationToken)
    {
        var connection = _context.Database.GetDbConnection();
        var closeConnection = connection.State != System.Data.ConnectionState.Open;

        if (closeConnection)
        {
            await connection.OpenAsync(cancellationToken);
        }

        try
        {
            await using var command = connection.CreateCommand();
            command.CommandText = """
                UPDATE dbo.UuidCounter
                SET CounterValue = CounterValue + 1
                OUTPUT INSERTED.CounterValue
                WHERE EntityType = @entityType;
                """;

            var transaction = _context.Database.CurrentTransaction;
            if (transaction is not null)
            {
                command.Transaction = transaction.GetDbTransaction();
            }

            var parameter = command.CreateParameter();
            parameter.ParameterName = "@entityType";
            parameter.DbType = System.Data.DbType.Byte;
            parameter.Value = entityType;
            command.Parameters.Add(parameter);

            var result = await command.ExecuteScalarAsync(cancellationToken);
            if (result is null || result == DBNull.Value)
            {
                throw new InvalidOperationException(
                    $"UUID counter for entity type '{entityType}' does not exist.");
            }

            return CreateUuidV7(entityType, Convert.ToInt64(result));
        }
        finally
        {
            if (closeConnection)
            {
                await connection.CloseAsync();
            }
        }
    }

    private static Guid CreateUuidV7(byte entityType, long counter)
    {
        var uuid = Guid.CreateVersion7();

        var hex = uuid.ToString("N");

        // Keep first 20 hex characters generated by UUID v7.
        // Replace final 12 characters with:
        // entity type + 11-character counter.
        var suffix = $"{entityType:X1}{counter:X11}";

        var forgeUuid = hex[..20] + suffix;

        return Guid.ParseExact(forgeUuid, "N");
    }
}
